"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
var graphql_tag_1 = require("graphql-tag");
var typeDefs = (0, graphql_tag_1.gql)(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  type Affiliate {\n    id: ID!\n    email: String!\n    name: String\n    refId: String\n    totalClicks: Int\n    totalCommissions: Int\n  }\n  \n  type AuthPayload {\n    token: String!\n    affiliate: Affiliate!\n  }\n\n  type Referral {\n    email: String\n    refId: String\n    event: String\n  }\n\n  type Query {\n    getAffiliates: [Affiliate!]!\n    getAffiliate(id: ID!): Affiliate\n    me: Affiliate\n    getReferrals: [Referral!]!\n    # getProductsList: [Product!]!\n  }\n\n  type Mutation {\n    login(email: String!, password: String!): AuthPayload!\n    registerAffiliate(\n      email: String!\n      name: String\n      refId: String!\n      totalClicks: Int\n      totalCommissions: Int\n      password: String\n    ): AuthPayload!\n\n    updateAffiliate(\n      id: ID!\n      name: String\n      email: String\n      totalClicks: Int\n      totalCommissions: Int\n    ): Affiliate\n\n    deleteAffiliate(id: ID!): Affiliate\n\n    logClick(refId: String!): Boolean\n\n    trackReferral(email: String, refId: String, event: String): Referral\n\n  }\n"], ["\n  type Affiliate {\n    id: ID!\n    email: String!\n    name: String\n    refId: String\n    totalClicks: Int\n    totalCommissions: Int\n  }\n  \n  type AuthPayload {\n    token: String!\n    affiliate: Affiliate!\n  }\n\n  type Referral {\n    email: String\n    refId: String\n    event: String\n  }\n\n  type Query {\n    getAffiliates: [Affiliate!]!\n    getAffiliate(id: ID!): Affiliate\n    me: Affiliate\n    getReferrals: [Referral!]!\n    # getProductsList: [Product!]!\n  }\n\n  type Mutation {\n    login(email: String!, password: String!): AuthPayload!\n    registerAffiliate(\n      email: String!\n      name: String\n      refId: String!\n      totalClicks: Int\n      totalCommissions: Int\n      password: String\n    ): AuthPayload!\n\n    updateAffiliate(\n      id: ID!\n      name: String\n      email: String\n      totalClicks: Int\n      totalCommissions: Int\n    ): Affiliate\n\n    deleteAffiliate(id: ID!): Affiliate\n\n    logClick(refId: String!): Boolean\n\n    trackReferral(email: String, refId: String, event: String): Referral\n\n  }\n"])));
exports.default = typeDefs;
var templateObject_1;
